# Generated by Django 5.0.3 on 2024-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='This is your birth date', null=True, verbose_name='Birth Date'),
        ),
    ]
